version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'nonstop'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'nonstop'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    restart: always
    container_name: backend_app
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/home/app
      - /home/app/node_modules/
    ports:
      - "8000:8000"
    command: >
      sh -c "npm run dev"
    environment: 
      - PORT=8000
    depends_on: 
      db:
        condition: service_started

